// <auto-generated />
using System;
using BookAPI.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BookAPI.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0797bde0-8d73-4727-ab4f-4bccf80dbac9"),
                            Description = "Сказка о царе Салта́не, о сыне его славном и могучем богатыре князе \r\n                    Гвидо́не Салта́новиче и о прекрасной царевне Лебеди» — сказка в стихах Александра Пушкина, \r\n                    написанная в 1831 году и впервые изданная в следующем году в собрании стихотворений",
                            Name = "Сказка о царе Салтане",
                            Price = 127m
                        },
                        new
                        {
                            Id = new Guid("dab6a59a-aa04-4590-ab2a-0facab0f0b73"),
                            Description = "Ска́зка о рыбаке́ и ры́бке» — сказка А. С. Пушкина. Написана 2 октября 1833 года.\r\n                                Впервые напечатана в 1835 году в журнале «Библиотека для чтения»",
                            Name = "Сказка о золотой рыбке",
                            Price = 201m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
